import "../../styles/globals.css";
import { Rubik } from "next/font/google";
import Header from "@/components/common/Header"; // Update the path if necessary
import { SpeedInsights } from "@vercel/speed-insights/next";

const rubik = Rubik({
  weight: ["300", "400", "600", "800"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "eyesonnumber",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={rubik.className}>
      <link rel="icon" href="/favicon.ico" />
      <body className="bg-brand-50 overflow-hidden">
        <Header />
        <main className="pt-16">{children}</main> <SpeedInsights />
        {/* Add padding to prevent overlap */}
      </body>
    </html>
  );
}
