import '../../styles/globals.css'
import { Rubik } from 'next/font/google'
 
const rubik = Rubik({
  weight: ['300','400','600','800'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={rubik.className}>
      <body className='bg-brand-50 '>{children}</body>
    </html>
  )
}
